# Generated by Django 3.1.4 on 2020-12-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201227_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
