# Generated by Django 3.1.4 on 2020-12-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
